# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        Corebundle\Entity\User: 
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        DataBase:
            entity:
                class: CoreBundle\Entity\User
                property: email
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
     
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            
            anonymous: true
           
            provider: DataBase
            pattern: ^/
            user_checker: CoreBundle\Security\UserChecker
            
            form_login:
                success_handler: core.login.listener
                login_path: login
                check_path: login 
                
            logout:
                handlers: [core.logout.listener]
                path: logout
                target: login
                
                
    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MODERATOR]  
                
    access_control:
        
        - { path: ^/home/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       
   