<?php

/**
 * author: CHU VAN Jimmy 
 */

namespace BackendBundle\Repository;

/**
 * PostControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostControlRepository extends \Doctrine\ORM\EntityRepository
{
}
