<?php

/**
 * author: CHU VAN Jimmy
 */
namespace CoreBundle\Repository;

/**
 * PictureProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
