<?php

/**
 * author : CHU VAN Jimmy
 */

namespace CoreBundle\Repository;

use CoreBundle\Entity\Post;
use CoreBundle\Entity\User;
use CoreBundle\Entity\PostLike;

/**
 * PostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLikeRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Fonction qui retourne le nombre de like et dislike d'un utilisateur
     * 
     * @param User
     */
    public function countLikeAndDislikeByUser(User $user)
    {

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $result = $queryBuilder ->select('COUNT(pl)')
                                ->from(PostLike::class, 'pl')
                                ->where('pl.userConcerned = :user')
                                ->setParameter('user', $user)
                                ->getQuery();

        return $result->getScalarResult();

    }

    /**
     * Fonction qui retourne le nombre de like d'un utilisateur
     * 
     * @param User
     */
    public function countLikeByUser(User $user)
    {

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $result = $queryBuilder ->select('COUNT(pl)')
                                ->from(PostLike::class, 'pl')
                                ->where('pl.userConcerned = :user AND pl.like = true')
                                ->setParameter('user', $user)
                                ->getQuery();

        return $result->getSingleScalarResult();

    }

    /**
     * Fonction qui retourne le nombre de dislike d'un utilisateur
     * 
     * @param User
     */
    public function countDislikeByUser(User $user)
    {

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $result = $queryBuilder ->select('COUNT(pl)')
                                ->from(PostLike::class, 'pl')
                                ->where('pl.userConcerned = :user AND pl.like = false')
                                ->setParameter('user', $user)
                                ->getQuery();

        return $result->getSingleScalarResult();

    }

}
