<?php

/**
 * author: CHU VAN Jimmy
 */
namespace CoreBundle\Repository;

use CoreBundle\Entity\Post;
use CoreBundle\Entity\User;
use CoreBundle\Entity\Sujet;
use CoreBundle\Entity\PostLike;
use Doctrine\ORM\Query\Expr\Join;
use BackendBundle\Entity\PostControl;
use CoreBundle\Entity\PictureProfile;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retourne tous les commentaires d'un sujet
     * 
     * @param array
     */
    public function fetchAll( $options = array() )
    {

        $queryBuilder   = $this->getEntityManager()->createQueryBuilder();  
        $countLike      = $this->countLike();
        $countDisLike   = $this->countDisLike();

        if ( array_key_exists('user', $options) && 'anon.' !== $options['user'] ) {
                

            /***********************************************************************************
             *              Requête utilisée par les utilisateurs connectés
             **********************************************************************************/
            $result = $queryBuilder ->select('p.id, p.commentaire, p.date, u.username, u.id as id_user, pp.pictureName, pp.id as pictureID, pp.pictureExtension, pc.id as reclamationID')
                                    ->addSelect('('.$countLike.') as nbLike')
                                    ->addSelect('('.$countDisLike.') as nbDisLike')
                                    ->from(Post::class, 'p') 
                                    ->where('p.sujet = :sujet')
                                    ->leftJoin(
                                        PictureProfile::class, 
                                        'pp',
                                        \Doctrine\ORM\Query\Expr\Join::WITH,
                                        'pp.user = p.user'  
                                    )
                                    ->leftJoin(
                                        PostControl::class, 
                                        'pc',
                                        \Doctrine\ORM\Query\Expr\Join::WITH,
                                        'pc.user = :user AND pc.post = p.id'
                                    )
                                    ->innerJoin(User::class, 'u')
                                    ->andWhere('p.user = u.id')
                                    ->setParameters([
                                        'sujet' => $options['sujet'],
                                        'user'  => $options['user']
                                    ])
                                    ->orderBy('p.date', 'ASC')
                                    ->getQuery();  
                                    
        } else {

            /***********************************************************************************
             *              Requête utilisée par les utilisateurs non connectés
             **********************************************************************************/
            $result = $queryBuilder ->select('p.id, p.commentaire, p.date, u.username, u.id as id_user, pp.pictureName, pp.id as pictureID, pp.pictureExtension')
                                    ->addSelect('('.$countLike.') as nbLike')
                                    ->addSelect('('.$countDisLike.') as nbDisLike')
                                    ->from(Post::class, 'p') 
                                    ->where('p.sujet = :sujet')
                                    ->leftJoin(
                                        PictureProfile::class, 
                                        'pp',
                                        \Doctrine\ORM\Query\Expr\Join::WITH,
                                        'pp.user = p.user'        
                                    )
                                    ->innerJoin(User::class, 'u')
                                    ->andWhere('p.user = u.id')
                                    ->setParameters([
                                        'sujet' => $options['sujet']
                                    ])
                                    ->orderBy('p.date', 'ASC')
                                    ->getQuery();
                                     
        }   
      
        return $result->getResult();

    }
    
    /**
     * Retourne les commentaires signalés en fonction des filtres sélectionnés
     * 
     * @param array
     */
    public function fetchAllAdmin( $options = array() )
    {

        $queryBuilder     = $this->getEntityManager()->createQueryBuilder();  
        $countLike        = $this->countLike();
        $countDisLike     = $this->countDisLike();
        $countSignalement = $this->countSignalement();

        if ( $options['sujet'] != 0 ) {

            /***********************************************************************************
             *      Requête utilisée par les admins pour voir les commentaires signalés
             **********************************************************************************/
            $result = $queryBuilder ->select('p.id, p.commentaire, p.date, u.username, u.id as id_user, pp.pictureName, pp.id as pictureID, pp.pictureExtension, pc.id as reclamationID, s.id as sujetID, s.libelle as sujetLibelle')
                                    ->addSelect('('.$countLike.') as nbLike')
                                    ->addSelect('('.$countDisLike.') as nbDisLike')
                                    ->addSelect('('.$countSignalement.') as nbSignalement')
                                    ->from(Post::class, 'p') 
                                    ->where('p.sujet = :sujet')
                                    ->leftJoin(PictureProfile::class, 'pp', Join::WITH, 'pp.user = p.user')
                                    ->innerJoin(PostControl::class, 'pc', Join::WITH, 'pc.post = p.id')
                                    ->innerJoin(User::class, 'u' , Join::WITH, 'p.user = u.id')
                                    ->innerJoin(Sujet::class, 's', Join::WITH, 's.id = p.sujet')
                                    ->setParameters([
                                        'sujet' => $options['sujet']
                                    ]); 

        } else {

            /***********************************************************************************
             *      Requête utilisée par les admins pour voir les commentaires signalés
             **********************************************************************************/
            $result = $queryBuilder ->select('p.id, p.commentaire, p.date, u.username, u.id as id_user, pp.pictureName, pp.id as pictureID, pp.pictureExtension, s.id as sujetID, s.libelle as sujetLibelle')
                                    ->addSelect('('.$countLike.') as nbLike')
                                    ->addSelect('('.$countDisLike.') as nbDisLike')
                                    ->addSelect('('.$countSignalement.') as nbSignalement')
                                    ->from(Post::class, 'p') 
                                    ->leftJoin(PictureProfile::class, 'pp', Join::WITH, 'pp.user = p.user')
                                    ->innerJoin(PostControl::class, 'pc', Join::WITH, 'p.id = pc.post')
                                    ->innerJoin(User::class, 'u' , Join::WITH, 'p.user = u.id')
                                    ->innerJoin(Sujet::class, 's', Join::WITH, 's.id = p.sujet');

        }

   
        /********************************************************* 
         *          Construction de la clause OrderBy
         ********************************************************/
        if ( $options['orderByDate'] == 1 || $options['orderBySignalement'] == 1 ) {

            if ( $options['orderByDate'] == 1 ) {
                $result->addOrderBy('p.date', 'ASC');
            } else {
                $result->addOrderBy('p.date', 'DESC');
            }

            if ( $options['orderBySignalement'] == 1 ) {
                $result->addOrderBy('nbSignalement', 'ASC');
            } else {
                $result->addOrderBy('nbSignalement', 'DESC');
            }

        }  else {
            $result->orderBy('p.date', 'DESC');
            $result->addOrderBy('nbSignalement', 'DESC');
        }

        return $result->getQuery()->getResult();

    }

    /**
     * Retourne la requête SQL qui sélectionne le nombre de like d'un commentaire
     */
    public function countLike()
    {

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $result = $queryBuilder ->select('COUNT(pl1)')
                                ->from(PostLike::class, 'pl1')
                                ->where('pl1.post = p.id AND pl1.like = true')
                                ->getDQL();

        return $result;

    }

    /**
     * Retourne la requête SQL qui sélectionne le nombre de dislike d'un commentaire
     */
    public function countDisLike()
    {

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();  

        $result = $queryBuilder ->select('COUNT(pl2)')
                                ->from(PostLike::class, 'pl2')
                                ->where('pl2.post = p.id AND pl2.like = false')
                                ->getDQL();

        return $result;

    }

    /**
     *  Retourne la requête SQL qui sélectionne le nombre de signalement d'un commentaire
     */
    public function countSignalement()
    {

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();  

        $result = $queryBuilder ->select('COUNT(cs)')
                                ->from(PostControl::class, 'cs')
                                ->where('cs.post = p.id')
                                ->getDQL();

        return $result;

    }
    

}
