<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Sujet;
use BackendBundle\Entity\Theme;
 

/**
 * SujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetRepository extends \Doctrine\ORM\EntityRepository
{

     /**
     * Recherche d'un sujet dans un thème ou une section spécifique
     */
    public function fetchAllSubject($options = array())
    {

        $queryBuilder  = $this->getEntityManager()->createQueryBuilder();  
        
        if (array_key_exists('section', $options)) {
            
            $result = $queryBuilder ->select('u')
                                    ->from(Sujet::class, 'u')
                                    ->where('u.section = :section')
                                    ->setParameters([
                                        'section'   => $options['section']
                                    ])
                                    ->orderBy('u.date', 'DESC')
                                    ->getQuery();

        } else {

            $result = $queryBuilder ->select('u')
                                    ->from(Sujet::class, 'u')
                                    ->where('u.theme = :theme')
                                    ->setParameters([
                                        'theme'   => $options['theme']
                                    ])
                                    ->orderBy('u.date', 'DESC')
                                    ->getQuery();

        }

        return $result->getArrayResult();
     
    }

    /**
     * Recherche d'un sujet dans un thème ou une section spécifique
     */
    public function fetchSubjectByLibelle($options = array())
    {

        $queryBuilder  = $this->getEntityManager()->createQueryBuilder();  
        
        if (array_key_exists('section', $options)) {
            
            $result = $queryBuilder ->select('u')
                                    ->from(Sujet::class, 'u')
                                    ->where('u.libelle LIKE :libelle AND u.section = :section')
                                    ->setParameters([
                                        'libelle' => "%".$options['libelle']."%", 
                                        'section'   => $options['section']
                                    ])
                                    ->orderBy('u.date', 'DESC')
                                    ->getQuery();

        } else {

            $result = $queryBuilder ->select('u')
                                    ->from(Sujet::class, 'u')
                                    ->where('u.libelle LIKE :libelle AND u.theme = :theme')
                                    ->setParameters([
                                        'libelle' => "%".$options['libelle']."%", 
                                        'theme'   => $options['theme']
                                    ])
                                    ->orderBy('u.date', 'DESC')
                                    ->getQuery();

        }

        return $result->getArrayResult();
     
    }

}
